### ISSUE TITLE
Direct 连接可能失败，需要重试

### ISSUE THREAD

**Issue by huacnlee** [huacnlee/flora-kit#1]

**Comment by owengaozhen** [comment]
must specify server address, password and both server/local port
这个如何设置？？

**Comment by owengaozhen** [comment]
@huacnlee

**Comment by aloasut** [comment]
这个问题很明显，现在是国内的网站例如雪球direct的等无法访问，反而需要proxy的就很快。
表现就是浏览器打开地址以后，过好一会才出现 direct xueqiu.com的日志，而且这个访问直接就等到超时了。
