### ISSUE TITLE
FINAL,PROXY 没起作用

### ISSUE THREAD

**Issue by okjaketo** [huacnlee/flora-kit#15]
当我把规则设置成这样的时候，不能用谷歌：
`GEOIP,CN,DIRECT`
`FINAL,PROXY`
但是如果我再加这样一条规则，就可以用谷歌：
`DOMAIN-KEYWORD,google,PROXY`
请问这是什么原因造成的？

**Comment by mokeoo** [comment]
能贴个配置来看看不？
