### ISSUE TITLE
求文档

### ISSUE THREAD

**Issue by Menci** [huacnlee/flora-kit#16]
看 issue 里大家说的，好像可以写配置规则，有没有相关的文档呢

另外这里的配置规则可以在 Linux 中应用到全系统吗？据我所知现在 Linux 下 system-wide 自动代理没有好的解决方案。

如果不行的话，那我只将它作为一个 SS 客户端，和 sslocal 有区别吗？

**Comment by mokeoo** [comment]
支持surge配置：）
