### ISSUE TITLE
ubuntu无法运行

### ISSUE THREAD

**Issue by owengaozhen** [huacnlee/flora-kit#2]
./flora-kit: 4: ./flora-kit: Syntax error: Unterminated quoted string

**Comment by huacnlee** [comment]
那个编译时 for Mac OS 的

**Comment by huacnlee** [comment]
Ubuntu 需要下载源代码自行编译

**Comment by huacnlee** [comment]
此外，内部有调用 macOS 的网络设置命令，Ubuntu 没法跑

**Comment by owengaozhen** [comment]
2016/11/23 10:17:50 exec: "networksetup": executable file not found in $PATH
2016/11/23 10:17:50 
2016/11/23 10:17:50 exec: "networksetup": executable file not found in $PATH
2016/11/23 10:17:50 
must specify server address, password and both server/local port

**Comment by owengaozhen** [comment]
@huacnlee 还是不行阿？？

**Comment by huacnlee** [comment]
https://github.com/huacnlee/flora-kit/releases/tag/0.1.1
