### ISSUE TITLE
报错，求助

### ISSUE THREAD

**Issue by fhhan** [huacnlee/flora-kit#21]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1236ccf]

goroutine 61 [running]:
github.com/huacnlee/flora-kit/flora.(*ProxyConfig).GetProxyServer(0xc42011c000, 0xc4201fee34, 0xa, 0x0, 0x0)
	/Users/sean/dev_gopath/src/github.com/huacnlee/flora-kit/flora/config.go:162 +0x12f
github.com/huacnlee/flora-kit/flora.createRemoteConn(0x0, 0x0, 0x0, 0xc42049a060, 0xc420232380, 0x1e, 0x0, 0x0, 0x21, 0x102)
	/Users/sean/dev_gopath/src/github.com/huacnlee/flora-kit/flora/flora.go:217 +0x5c
github.com/huacnlee/flora-kit/flora.matchRuleAndCreateConn(0x130a980, 0xc4200bc0a0, 0xc420232380, 0x1e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sean/dev_gopath/src/github.com/huacnlee/flora-kit/flora/flora.go:152 +0xee
github.com/huacnlee/flora-kit/flora.handleConnection(0x130a980, 0xc4200bc0a0)
	/Users/sean/dev_gopath/src/github.com/huacnlee/flora-kit/flora/flora.go:115 +0x1e7
created by github.com/huacnlee/flora-kit/flora.Run
	/Users/sean/dev_gopath/src/github.com/huacnlee/flora-kit/flora/flora.go:81 +0x368

**Comment by youkale** [comment]
配置文件发一个看看

**Comment by fhhan** [comment]
@youkale 
[demo.conf.zip](https://github.com/huacnlee/flora-kit/files/2320865/demo.conf.zip)
 Thank you~

**Comment by youkale** [comment]
发了个新版本，你再试试

**Comment by fhhan** [comment]
还是不行，报错。。。

**Comment by youkale** [comment]
检查下你的proxy和proxygroup

**Comment by fhhan** [comment]
用了surge2和3的配置都不行。是不是配置文件太长，内容太多？

**Comment by youkale** [comment]
换v0.26呢？

**Comment by fhhan** [comment]
还是不行，😒

**Comment by youkale** [comment]
报错还是一样的吗？

**Comment by fhhan** [comment]
是的。。。很奇怪

**Comment by youkale** [comment]
🇯🇵= shadowsocks, ip, 8080, chacha20, password
🇯🇵e = shadowsocks, ip, 8080, chacha20, password
🇯🇵1 = shadowsocks, ip, 8080, chacha20, password
🇯🇵2 = shadowsocks, ip, 8080, chacha20, password
这里的名字 🇯🇵换一换，别搞emjio

**Comment by fhhan** [comment]
换了还是报错。。。

**Comment by youkale** [comment]
🍃 Proxy = select,🏃 Auto,🚀 Direct,🇯🇵, 🇯🇵e, 🇯🇵1, 🇯🇵2, sfo, Ushare
🍂 Domestic = select,🚀 Direct,🍃 Proxy
🍎 Only = select,🚀 Direct,🇯🇵, 🇯🇵e, 🇯🇵1, 🇯🇵2, sfo, Ushare
☁️ Others =  select,🚀 Direct,🍃 Proxy
🏃 Auto = url-test,sfo,🇯🇵2,🇯🇵1,Ushare,🇯🇵,🇯🇵e,url = http://www.gstatic.com/generate_204,interval = 1200
既然 🍃 Proxy,🍂 Domestic,🍎 Only ,☁️ Others 是翻墙组，为什么会包含 Auto, 🚀 Direct  ?
proxyGroup 只能包含proxy里的内容. 
而且我反复测试，你的这个配置文件在我这启动是没有报错的.

**Comment by fhhan** [comment]
不知道了，是不是我电脑缺依赖没安装？

**Comment by youkale** [comment]
不需要依赖的
