### ISSUE TITLE
有办法实现对 Windows 的运行吗？

### ISSUE THREAD

**Issue by laincat** [huacnlee/flora-kit#6]
如果可以，求运行方法步骤。。。

**Comment by mokeoo** [comment]
直接  ``` make build  ``` 就可以
Makefile已经加了

**Comment by huacnlee** [comment]
由于我没有 Windows 机器，不知道如何设置 Windows 的系统代理，其他部分目前编译好的，应该可以直接运行的

**Comment by laincat** [comment]
`2017/06/27 11:26:55 Floar 0.2.2
2017/06/27 11:26:55 WARN: Your not in macOS, Networksetup skiped. Please change Network proxy setting by manually.
2017/06/27 11:26:55 Listen socks 0.0.0.0:8889
2017/06/27 11:27:19 [twitter.com]➔[PROXY]√[twitter.com:443]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x54030f]

goroutine 18 [running]:
flora-kit/flora.loadProxyGroup.func2(0xc042166aa7, 0x7, 0x0)
        /Users/jason/work/src/flora-kit/flora/config.go:189 +0x16f
main.connectToServer(0xc042166aa7, 0x7, 0xc04219c123, 0xf, 0x104, 0xc0420080d0, 0xf, 0x2d, 0x0, 0x0, ...)
        /Users/jason/work/src/flora-kit/main.go:154 +0x5b
main.createServerConn(0xc042163360, 0xc04219c123, 0xf, 0x104, 0xc0420080d0, 0xf, 0x0, 0x0, 0x0, 0x0)
        /Users/jason/work/src/flora-kit/main.go:183 +0x110
main.handleConnection(0x641ec0, 0xc042054088)
        /Users/jason/work/src/flora-kit/main.go:216 +0x602
created by main.run
        /Users/jason/work/src/flora-kit/main.go:250 +0x2ff`

**Comment by laincat** [comment]
换了配置文件就可以了(https://github.com/huacnlee/flora-kit/raw/master/flora.default.conf)。赞！

求可用的参数和不可用的参数。。。详细说明！

**Comment by laincat** [comment]
url-test 还不能用是吗？

**Comment by laincat** [comment]
2017/06/27 11:41:06 [final]➔[PROXY]√[news.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[icons.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[news.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[img1.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[11.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[11.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[11.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[11.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[act.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[act.mydrivers.com:80]
2017/06/27 11:41:06 [final]➔[PROXY]√[static.anquan.org:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[news.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[img1.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[img1.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[img1.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[img1.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[img1.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[news.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[icons.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[icons.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[icons.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[icons.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[icons.mydrivers.com:80]
2017/06/27 11:41:07 [final]➔[PROXY]√[dt.mydrivers.com:80]

> GEOIP,CN,DIRECT 失效？

**Comment by laincat** [comment]
2017/06/27 11:46:26 [cnbeta.com]➔[DIRECT]√[www.cnbeta.com:80]
2017/06/27 11:46:27 [cnbeta.com]➔[DIRECT]√[www.cnbeta.com:80]
2017/06/27 11:46:27 [cnbeta.com]➔[DIRECT]√[www.cnbeta.com:80]
2017/06/27 11:46:27 [cnbetacdn.com]➔[DIRECT]√[static.cnbetacdn.com:80]
2017/06/27 11:46:27 [cnbetacdn.com]➔[DIRECT]√[static.cnbetacdn.com:80]
2017/06/27 11:46:27 [cnbetacdn.com]➔[DIRECT]√[static.cnbetacdn.com:80]
2017/06/27 11:46:27 [cnbetacdn.com]➔[DIRECT]√[static.cnbetacdn.com:80]
2017/06/27 11:46:27 [cnbetacdn.com]➔[DIRECT]√[static.cnbetacdn.com:80]
2017/06/27 11:46:27 [cnbetacdn.com]➔[DIRECT]√[static.cnbetacdn.com:80]
2017/06/27 11:46:28 [cnbeta.com]➔[DIRECT]√[www.cnbeta.com:80]

> cnbeta 又正常。。 冏

**Comment by mokeoo** [comment]
我也没有win，给别人编译win版本测试是可以跑的
